### PR TITLE
feat: add enhanced support for grid rows selection

### LINKED ISSUE #13: Shift+click for multiple selection
After [this issue](https://github.com/FlowingCode/TwinColGridAddon/issues/13) is implemented, then it would be nice to use shift+click in order to select multiple items in each grid.

### PR DESCRIPTION
**Pull request by flang**
Enables grid rows selection using arrow up/down, click, shift+click, shift+arrow up/down, ctrl+space and ctrl+click

Close #13

### CODE REVIEW

**Review by javier-godoy — CHANGES_REQUESTED** [review]
Compilation failed

**Comment by flang** [comment]
fixed

**Comment by flang** [comment]
Fixed

**Review by mlopezFC — APPROVED** [review]
LGTM

**Review by paodb — APPROVED** [review]

**Pull request merged**
